wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.13
    start_time: 1639039238
    t:
      1:
      - 1
      4: 3.6.13
      5: 0.12.7
      8:
      - 2
      - 3
      - 5
